name: ci
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name:  golangci-lint
        uses: golangci/golangci-lint-action@v2
      - run: golangci-lint run ./...
      - run: go test ./... -coverprofile=cover.out -covermode=atomic
      - uses: codecov/codecov-action@v2
        with: 
          files: ./cover.out


  build:
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", amd64, arm64]
        exclude:  
          - goarch: "386"
            goos: darwin 
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - run: mkdir -p ${{ matrix.goos }}/${{ matrix.goarch }}
    - run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build github.com/bart6114/butt -o ${{ matrix.goos }}/${{ matrix.goarch }}
    ## above is fine to get latest for now, also save a copy with short sha
    - id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - run: cp ${{ matrix.goos }}/${{ matrix.goarch }}/butt ${{ matrix.goos }}/${{ matrix.goarch }}/butt-${{ steps.vars.outputs.sha_short }}
    ## upload binary to google storage
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.gcp_credentials }}
    - uses: google-github-actions/upload-cloud-storage@v0.4.0
    - id: upload-files
      uses: google-github-actions/upload-cloud-storage@v0.4.0
      with:
        path: ${{ matrix.goos }}/${{ matrix.goarch }}
        destination: better-unified
