name: ci
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name:  golangci-lint
        uses: golangci/golangci-lint-action@v2
      - run: golangci-lint run ./...
      - run: go test ./... -coverprofile=cover.out -covermode=atomic
      - uses: codecov/codecov-action@v2
        with: 
          files: ./cover.out