name: main
on: push

jobs:
  tests:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
      run: go test ./...
    - name:  golangci-lint
      uses: golangci/golangci-lint-action@v2
      run: golangci-lint run ./...
  

